### PR TITLE
Use scrollWidth/Height instead of offsetWidth/Height

### PR DESCRIPTION
**Pull request by lewang**
We ran into a situation where the offsetWidth was capped by the parent, so the text didn't resize properly.

According to this: http://stackoverflow.com/questions/21064101/understanding-offsetwidth-clientwidth-scrollwidth-and-height-respectively , scroll\* should be used in this context anyway.

### CODE REVIEW

**Comment by STRML** [comment]
That is a really nice SO answer. Thanks for this.

**Comment by STRML** [comment]
I believe [L167](https://github.com/shifthealthparadigms/textFit/blob/master/textFit.js#L167) should be `scrollHeight` as well then, in this case?

**Comment by lewang** [comment]
I've force pushed an update.  "offset" no longer occurs in the code.

**Comment by STRML** [comment]
Thanks!

**Comment by STRML** [comment]
You're up on `2.2.1`.

**Comment by STRML** [comment]
@lewang To support fractional sizes / zoom, we've moved to `getBoundingClientRect()`. Before I release, can you recall the situation in which `offsetHeight/Width` was required? We can't reproduce it.

**Comment by lewang** [comment]
I don't recall this context, sorry.

**Pull request merged**
